version: '3.6'
services:
  function-lifecycle-broker:
    image: redis
    ports:
      - '6379'
    networks:
      - hermes-test

  function-orchestrator:
    build:
      context: ../
      target: testing
    environment:
      - DOCKER_BINARY_PATH=/usr/local/bin/docker
    ports:
      - 3000:3000
    networks:
      - hermes-test
    volumes:
      - ..:/app/server
      - ./tmp/results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - function-lifecycle-broker

networks:
  hermes-test:
    external: true
